project:
  type: website

website:
  title: "Chess analysis"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - sources.qmd
    
      - analysis.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true